### ISSUE TITLE
If the phone is in the dock, it crashes on boot.

### ISSUE THREAD

**Issue by epinter** [razrqcom-dev-team/android_kernel_motorola_msm8960-common#3]
Crash fixed.

**Comment by epinter** [comment]
last_kmsg (thanks Orphee from XDA):
http://pastebin.com/EHnPvysB

**Comment by pcarenza** [comment]
Also happens when plugged in via USB

**Comment by SkrilaxCZ** [comment]
Hmm, didn't happen to me so far (when plugged to USB, I don't have dock).
