### ISSUE TITLE
Random FC Issue

### ISSUE THREAD

**Issue by pcarenza** [razrqcom-dev-team/android_kernel_motorola_msm8960-common#8]
I think I found what's going on with the random Force Closes 
OpenGL is not initializing properly because the GPU is running out of memory
if I swipe away apps, the problem goes away for a while. If I turn off window animation, the problem goes away
I've done a lot of research... some say that increasing GPU memory by deallocating the from the camera fixes the issue. I'm a kernel n00b so I would have little idea as to how to do this right now.

https://code.google.com/p/cm9-wildfire-s/issues/detail?id=9

**Comment by epinter** [comment]
Not happening anymore
